LANGUAGES = {
    "Afrikaans": "af-ZA",
    "Amharic": "am-ET",
    "Arabic": "ar-SA",
    "Basque": "eu-ES",
    "Bulgarian": "bg-BG",
    "Catalan": "ca-ES",
    "Cantonese (Traditional)": "yue-Hant-HK",
    "Chinese (Mandarin - Simplified)": "zh-CN",
    "Chinese (Mandarin - Traditional)": "zh-TW",
    "Croatian": "hr-HR",
    "Czech": "cs-CZ",
    "Danish": "da-DK",
    "Dutch": "nl-NL",
    "English (US)": "en-US",
    "English (UK)": "en-GB",
    "Estonian": "et-EE",
    "Filipino": "fil-PH",
    "Finnish": "fi-FI",
    "French": "fr-FR",
    "German": "de-DE",
    "Greek": "el-GR",
    "Gujarati": "gu-IN",
    "Hebrew": "he-IL",
    "Hindi": "hi-IN",
    "Hungarian": "hu-HU",
    "Icelandic": "is-IS",
    "Indonesian": "id-ID",
    "Italian": "it-IT",
    "Japanese": "ja-JP",
    "Javanese": "jv-ID",
    "Kannada": "kn-IN",
    "Korean": "ko-KR",
    "Latvian": "lv-LV",
    "Lithuanian": "lt-LT",
    "Malay": "ms-MY",
    "Malayalam": "ml-IN",
    "Marathi": "mr-IN",
    "Nepali": "ne-NP",
    "Norwegian": "no-NO",
    "Persian": "fa-IR",
    "Polish": "pl-PL",
    "Portuguese (Brazil)": "pt-BR",
    "Portuguese (Portugal)": "pt-PT",
    "Punjabi": "pa-IN",
    "Romanian": "ro-RO",
    "Russian": "ru-RU",
    "Serbian": "sr-RS",
    "Slovak": "sk-SK",
    "Slovenian": "sl-SI",
    "Spanish (Spain)": "es-ES",
    "Spanish (Mexico)": "es-MX",
    "Swahili": "sw-KE",
    "Swedish": "sv-SE",
    "Tamil": "ta-IN",
    "Telugu": "te-IN",
    "Thai": "th-TH",
    "Turkish": "tr-TR",
    "Ukrainian": "uk-UA",
    "Urdu": "ur-PK",
    "Vietnamese": "vi-VN",
    "Zulu": "zu-ZA"
}